architecture: M1
cluster_name: efmdemo
cluster_tags:
  Owner: ton.machielsen@enterprisedb.com

cluster_vars:
  enable_pg_backup_api: false
  epas_redwood_compat: true
  failover_manager: efm
  postgres_version: '14'
  postgresql_flavour: epas
  preferred_python_version: python3
  use_volatile_subscriptions: false

docker_networks:
- ipam_config:
  - subnet: 192.168.17.0/24
  name: tpanet

locations:
- Name: main
- Name: dr

instance_defaults:
  image: tpa/ubuntu:20.04
  platform: docker
  vars:
    ansible_user: root

instances:
- Name: pg1
  backup: barmansrv
  location: main
  node: 1
  networks:
  - ipv4_address: 192.168.17.11
    name: tpanet
  role:
  - primary
  - pem-agent
- Name: pg2
  location: main
  node: 2
  networks:
  - ipv4_address: 192.168.17.12
    name: tpanet
  role:
  - replica
  - pem-agent
  upstream: pg1
- Name: barmansrv
  location: main
  node: 3
  networks:
  - ipv4_address: 192.168.17.13
    name: tpanet
  role:
  - barman
  - log-server
  - monitoring-server
- Name: pg3
  location: dr
  node: 4
  networks:
  - ipv4_address: 192.168.17.14
    name: tpanet
  role:
  - replica
  - pem-agent
  upstream: pg2
- Name: pemserver
  location: main
  node: 5
  networks:
  - ipv4_address: 192.168.17.15
    name: tpanet
  role:
  - pem-server

